**<u>Linear Algebra With Python & Numpy</u>**

Hi there. Here is a page where I try out some linear algebra functions in Python with the Numpy package.

**<u>Sections</u>**

* Python's Numpy Package
* Part One - Vectors
* Part Two - Matrices

<u>**Python's Numpy Package**</u>

The Numpy package in Python stands for numerical Python. This package contains a lot of functions for mathematics, statistics and for linear algebra.

In [2]:
# Numpy Work With Linear Algebra
# References: Python For Data Analysis
# https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

import numpy as np

**<u>Part One - Vectors</u>**

This first section deals with vectors while the next section deals with matrices.

We start with creating two vectors and performing vector addition and subtraction. The two vectors are $\textbf{a} = (1, -1, 2)$ and $\textbf{b} = (2, -1, 3)$.

In [3]:
## Vectors:

a = np.array([1, -1, 2])
b = np.array([2, -1, 3])

print(a)
print(b)

[ 1 -1  2]
[ 2 -1  3]


When it comes to vector addition and vector subtraction the operation performs element wise.

In [4]:
print(a + b) # Vector addition
print(a - b) # Vector subtraction

[ 3 -2  5]
[-1  0 -1]


Scalar multiplication is when a vector is multiplied by a number.

In [5]:
print(5*a) # Scalar multiplication on vector

[ 5 -5 10]


<u>Dot Product</u>

The dot product of two vectors consists of element wise multiplication and then taking the sum of the products.

In [6]:
# Dot Product (Element wise multiplication and take sum of products):

print(np.dot(a, b)) # (1*2) + (-1)(-1) + 2*3 = 2 + 1 + 6 = 9

9


<u>Cross Product</u>

Given two vectors, the cross product vector is a third vector that is perpendicular/orthogonal (or is 90 degrees) to both the two vectors.

In [8]:
# Cross Product (A Vector That Is Perpendicular/Orthogonal To Vectors a and b):

cross_vect = np.cross(a, b)
print(cross_vect)

[-1  1  1]


To make sure that the vector (-1, 1, 1) is truly a cross product vector to (1, -1, 2) and (2, -1, 3), we take the dot products between each of the two vectors and (-1, 1, 1).

In [9]:
# Check orthognality by seeing dot product is zero between cross product with a and b:

print(np.dot(cross_vect, a))

print(np.dot(cross_vect, b))

0
0


<u>Vector Of Random Numbers</u>

In Numpy, you can create a vector of random numbers. In this example, I create four normally distributed random numbers.

In [10]:
# Vector with random numbers from a normal distribution.

print(np.random.normal(size = (1, 4)))

[[ 1.31267963 -0.25954768 -1.22271547 -0.11765921]]


<u>A Function Example</u>

You can feed in values from a Numpy array into a function. In this example, I have a Numpy array of 0, 1, 2 and 3 and I feed those numbers into a simple exponential function.

In [11]:
# Function example:

x = np.array([0, 1, 2, 3])

print(np.exp(x))

[  1.           2.71828183   7.3890561   20.08553692]


**<u>Part Two - Matrices</u>**

This section starts with a few special matrices.

In [12]:
## Matrices:

# 5 by 5 Identity Matrix

identity_five = np.identity(5)

print(identity_five)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [13]:
# 3 by 3 Matrix of zeroes:

print(np.zeros( (3, 3)))

# 3 by 3 Matrix of ones:

print(np.ones( (3, 3)))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In Numpy, matrices are created by rows and not by columns in `np.array()`. The matrix A is created in this form:

$$\text{A} = \begin{bmatrix}
    1     & 5 & 2 \\
    2     & 3 & -1\\
   0   & 1 & -5 \\
\end{bmatrix} $$

In [14]:
# Creating a matrix:

A = np.array([[1., 5., 2.], [2., 3.,-1.], [0., 1., -5.]])

print(A)

[[ 1.  5.  2.]
 [ 2.  3. -1.]
 [ 0.  1. -5.]]


<u>Matrix Determinants</u>

In [15]:
# Matrix determinant:

det_A = np.linalg.det(A)

print(det_A)

40.0


<u>Diagonal Of A Matrix</u>

In [17]:
# Diagonal of Matrix:

print(np.diag(A))

[ 1.  3. -5.]


<u>Trace Of A Matrix</u>

In [18]:
# Trace Of A Matrix:

print(np.trace(A))

-1.0


<u>Transpose Of A Matrix (Switch Rows With Columns & Vice Versa)</u>

In [20]:
# Transpose Of Matrix:

print(np.transpose(A)) # Transpose of matrix A

[[ 1.  2.  0.]
 [ 5.  3.  1.]
 [ 2. -1. -5.]]


<u>Inverse Of A Square Matrix</u>

In [22]:
# Inverse Of A Square Matrix:

print(np.linalg.inv(A))

[[-0.35   0.675 -0.275]
 [ 0.25  -0.125  0.125]
 [ 0.05  -0.025 -0.175]]


<u>Eigenvalues & Eigenvectors Of A Square Matrix</u>

In [24]:
# Eigenvalues and Eigenvectors Of A Square Matrix:

print(np.linalg.eig(A))

(array([ 5.31205954, -1.59702758, -4.71503196]), array([[-0.76793053,  0.89996329, -0.49933346],
       [-0.63754246, -0.41827952,  0.23744618],
       [-0.06182494, -0.12291593,  0.83323791]]))


<u>Matrix Multiplication</u>

In [25]:
# Matrix multiplication:

B = np.array([[1, 3], [1, 2]]) # 2 by 2 matrix

D = np.array([[2], [-1]]) # 2 by 1 matrix

print(np.matmul(B, D))

[[-1]
 [ 0]]


<u>Solving A Linear System</u>

In [27]:
# Solving a linear system example Bx = c.

B = np.array([[1, 3], [1, 2]])

c = np.array([[2], [0]])

print(np.linalg.solve(B, c))

[[-4.]
 [ 2.]]
